# Generated by Django 5.1.3 on 2024-11-28 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transcription', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transcription',
            name='duration',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='transcription',
            name='segments',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
